In [1]:
import torch
import numpy as np

In [12]:
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
], dtype=torch.float32)

In [3]:
t.sum(dim=0)

tensor([2, 4, 2])

In [4]:
t.sum(dim=1)

tensor([1, 4, 3])

In [5]:
t.sum()

tensor(8)

In [10]:
t.prod()

tensor(0)

In [13]:
t.mean()

tensor(0.8889)

In [14]:
t.std()

tensor(1.1667)

### Argmax

In [15]:
t

tensor([[0., 1., 0.],
        [2., 0., 2.],
        [0., 3., 0.]])

In [16]:
t.max()

tensor(3.)

In [17]:
t.max(dim=0)

(tensor([2., 3., 2.]), tensor([1, 2, 1]))

In [18]:
t.argmax(dim=0)

tensor([1, 2, 1])

In [19]:
t.max(dim=1)

(tensor([1., 2., 3.]), tensor([1, 2, 1]))

In [20]:
t.argmax(dim=1)

tensor([1, 2, 1])

In [22]:
t.max(dim=1)[0].tolist()

[1.0, 2.0, 3.0]