In [1]:
# 20190521

In [2]:
import torch

In [3]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [4]:
t.size()

torch.Size([3, 4])

In [5]:
t.shape

torch.Size([3, 4])

In [6]:
len(t.shape)

2

In [8]:
torch.tensor(t.shape).prod().item() # 4 x 3 = 12, 元素个数

12

In [9]:
t.numel() # number of elements, 元素的个数

12

In [10]:
t

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [11]:
t.reshape(2,6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [12]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [14]:
t.reshape(6, 2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [16]:
# squeeze
t.reshape(1,12).squeeze()

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [19]:
torch.flatten(t) # 等同于reshape && squeeze

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [21]:
# Tensor之间的连接
t1 = torch.tensor([
    [1,2],
    [3,4]
])

t2 = torch.tensor([
    [5,6],
    [7,8]
])

In [26]:
torch.cat((t1, t2), dim=0).shape

torch.Size([4, 2])

In [23]:
torch.cat((t1, t2), dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

上面的这个例子可以作为基本情况，来辅助我们理解如何使用`dim`.

In [25]:
torch.stack((t1,t2)).shape

torch.Size([2, 2, 2])

### stack

In [27]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
])

t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
])


In [28]:
t = torch.stack((t1, t2, t3))
t.shape

torch.Size([3, 4, 4])

In [29]:
t = t.reshape(3,1,4,4)

In [30]:
t

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [34]:
res = t.flatten(start_dim=1) # 保留batch_size这个轴，将每张图片展平

In [35]:
res.shape

torch.Size([3, 16])

In [36]:
res

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])