In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.16.3


In [3]:
import torch

In [10]:
# 创建一个张量并设置 requires_grad=True 用来追踪他的计算历史
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [5]:
y = x + 3
print(y)

tensor([[4., 4.],
        [4., 4.]], grad_fn=<AddBackward0>)


In [7]:
print(y.grad_fn)

In [8]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[48., 48.],
        [48., 48.]], grad_fn=<MulBackward0>) tensor(48., grad_fn=<MeanBackward1>)


In [9]:
a = torch.randn(2, 2)

`autograd`包为张量上的所有操作提供了自动求导，反向传播是根据代码确定执行。