### WHAT IS PYTORCH?
It’s a Python-based scientific computing package targeted at two sets of audiences:

- A replacement for NumPy to use the power of GPUs
- a deep learning research platform that provides maximum flexibility and speed

ALL from https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[-3.4775e+15,  4.5808e-41, -3.4775e+15],
        [ 4.5808e-41,  1.1720e-19,  1.5637e-01],
        [ 1.8475e+20,  6.2642e-10,  7.5570e+28],
        [ 7.7140e+31,  1.1703e-19,  5.8253e-10],
        [ 1.0314e-08,  1.7377e-04,  2.7449e-06]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5232, 0.3447, 0.7606],
        [0.8457, 0.3157, 0.0531],
        [0.1944, 0.8298, 0.6754],
        [0.6477, 0.9116, 0.3823],
        [0.4606, 0.7690, 0.5979]])


In [4]:
x = torch.randn(5, 3)
print(x)

tensor([[ 1.2169,  0.4813,  0.8184],
        [-1.0133,  0.1184,  0.9474],
        [-0.9416, -0.8702, -0.0297],
        [-0.9443, -0.3209, -0.4853],
        [ 0.2727, -0.4687, -1.0015]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
# Construct a tensor directly from data:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
type(x)

torch.Tensor

In [12]:
# reuse existing tensor
x = x.new_ones(5, 3, dtype=torch.double) # 复用形状
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [11]:
x = torch.randn_like(x, dtype=torch.float) # 重写类型
print(x)

tensor([[ 1.5379, -1.3608,  1.8991],
        [-1.2652, -1.8471, -1.0980],
        [ 1.8871,  0.0402,  2.4770],
        [ 1.1372,  0.9632, -0.5171],
        [-0.5967, -1.4552, -1.7057]])


In [13]:
print(x.size())

torch.Size([5, 3])


In [14]:
x.size()[0]

5

Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

In [19]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)

In [20]:
x + y

tensor([[0.5878, 1.2253, 1.4355],
        [1.9855, 0.4235, 1.1519],
        [1.2164, 0.3259, 0.4557],
        [0.2742, 1.4050, 1.0424],
        [0.6247, 0.7974, 0.7798]])

In [26]:
y.add_(x) # 原地修改y

tensor([[1.0000, 2.1136, 2.1368],
        [2.9731, 0.7901, 1.9428],
        [1.5141, 0.6139, 0.6900],
        [0.4959, 2.0877, 1.8287],
        [0.7939, 1.3220, 1.4124]])

In [25]:
y

tensor([[0.5878, 1.2253, 1.4355],
        [1.9855, 0.4235, 1.1519],
        [1.2164, 0.3259, 0.4557],
        [0.2742, 1.4050, 1.0424],
        [0.6247, 0.7974, 0.7798]])

In [27]:
print(x[: 1])

tensor([[0.4121, 0.8883, 0.7013]])


In [28]:
# resize, reshape ==> torch.view
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # -1表示自动推断
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [35]:
c = x[0][0].item() # 通过item()将数据类型转换为Python原生类型

In [34]:
print(c)
print(type(c))

3.8373208045959473
<class 'float'>


### Convert Torch Tensor to Numpy array

In [36]:
# Numpy
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [37]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [38]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Numpy Array转为Torch Tensor

In [39]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


### 在CUDA上计算

In [41]:
if torch.cuda.is_available():
    device = torch.device('cuda') # a cuda object
    y = torch.ones_like(x, device=device)
    x = x.to(device) # or x.to('cuda')
    z = x + y
    print(z)
    print(z.to('cpu', torch.double))

tensor([[ 4.8373, -0.2691, -0.1407,  0.1573],
        [ 2.0038,  1.2784,  0.2163,  2.4003],
        [ 0.4032,  0.9470,  0.2772,  1.4627],
        [ 1.4676,  0.9388,  0.0509,  0.0838]], device='cuda:0')
tensor([[ 4.8373, -0.2691, -0.1407,  0.1573],
        [ 2.0038,  1.2784,  0.2163,  2.4003],
        [ 0.4032,  0.9470,  0.2772,  1.4627],
        [ 1.4676,  0.9388,  0.0509,  0.0838]], dtype=torch.float64)
