In [1]:
import torch
import numpy as np

In [2]:
print(torch.__version__)

1.0.1


In [3]:
torch.cuda.is_available()

True

In [4]:
torch.version.cuda

'10.0.130'

In [5]:
data = np.array([1,2,3])

In [7]:
t1 = torch.Tensor(data) # 构造函数
t2 = torch.tensor(data) # 工厂函数
t3 = torch.as_tensor(data) # 工厂
t4 = torch.from_numpy(data) # 工厂

In [8]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [9]:
torch.get_default_dtype()

torch.float32

In [10]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int64
torch.int64
torch.int64


In [13]:
torch.tensor(np.array([1,2,3]), dtype=torch.float64) # 显式指定类型

tensor([1., 2., 3.], dtype=torch.float64)

### 存储位置一览

In [14]:
# 修改data
data[0] = 0
data[1] = 0
data[2] = 0

In [15]:
print(t1)
print(t2)

tensor([1., 2., 3.])
tensor([1, 2, 3])


In [16]:
print(t3)
print(t4)

tensor([0, 0, 0])
tensor([0, 0, 0])


t3, t4指向的是原先的数据